### ISSUE TITLE
能否将分支ccnu中改动的内容合并到基线分支master中？

### ISSUE THREAD

**Issue by liuqun** [nanpuyue/OH3C#3]
humiaozuzu，你好！

ccnu分支中提交代码时只写了一句fix a lot of issue，不够严谨。建议：将改动精华部分整理好以后再重新提交到基线master之中

—— 阿群

**Comment by nanpuyue** [comment]
嗯，这个等luci支持的代码稳定后再做吧，因为主程序还要修改以适应luci。

**Comment by liuqun** [comment]
把luci的代码放到github上来，单独建立一个测试分支
