### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'int' objects 

### ISSUE THREAD

**Issue by rve** [nanpuyue/OH3C#4]
Decice(Press "Enter" to use eth1 as default): eth1.1
MAC(Press "Enter" if you don't need to use binding MAC-address): 
Traceback (most recent call last):
  File "oh3c.py", line 79, in <module>
    main()
  File "oh3c.py", line 68, in main
    line_of_mac = macmgr.get_line_of_mac("'wan'")
  File "/OH3C/oh3c/macmgr.py", line 77, in get_line_of_mac
    i = get_info_of(interface)
  File "/OH3C/oh3c/macmgr.py", line 42, in get_info_of
    b = seek_in_list('config',config_list,a+1)
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by rve** [comment]
My device : rg100a
My openwrt version: rg100a-openwrt.org.cn-10.03.233-DIY-full-0722.bin

**Comment by rve** [comment]
My python skill is so poor...
Part of /etc/config/network that i think is concerned:

config 'interface' 'lan'  
        option 'type' 'bridge'  
        option 'ifname' 'eth1.0'  
        option 'proto' 'static'  
        option 'ipaddr' '192.168.1.1'
        option 'netmask' '255.255.255.0'
        option 'nat' '1'  
        option 'defaultroute' '0'  
        option 'peerdns' '0'         

config 'interface' 'wan'  
        option 'ifname' 'eth1.1'  
        option 'proto' 'dhcp'  
        option 'defaultroute' '0'  
        option 'peerdns' '0'            

~

**Comment by nanpuyue** [comment]
可不可以用中文呢。。。
你使用的版本太旧了，这是个小bug，在后来的版本中已经修正了～

**Comment by nanpuyue** [comment]
你可以下载oh3c_0.21_brcm63xx.ipk安装，因为luci版的和dreambox有点不兼容，所以暂时不建议你使用，当然，你也可换trunk版的openwrt，今天刚好弄了一个rg100a的trunk版固件，发你邮箱了，刷了过后可以用luci版的OH3C：luci-app-oh3c_all.zip ，用scp上传到路由器即可。

**Comment by rve** [comment]
哦，膜拜大大，我是SYSU的，就是说，最合适的版本是dreambox之前的最新版？ 然后今天下午我同学（zhangyaofeng）发我你新编译的rg100a的trunk版固件了，可是貌似有些问题，我们刷了之后都死了，就是ping不到，telnet不到。。然后我才又刷了这个。
然后maple大大说因为rg100a的vlan的问题，他以前折腾过，失败了。但是现在的新rg100a固件貌似已经没有vlan了，所以说没有这方面问题吧？

**Comment by nanpuyue** [comment]
都死了啊。。。
真是极品路由器啊～
那个固件是我用ImageBuilder生成的，居然给刷死了～

**Comment by rve** [comment]
forgot to close... sorry
